#!/bin/bash

opts=$1

command_head="rg $opts -l '$2'"
shift 2

while (("$#")) && [ "$1" != -- ] ; do
  command_tail+="| xargs --null rg $opts -l '$1' "
  shift
done
shift

eval "$command_head $@ $command_tail | xargs --null rg $opts -m 1 ^= "
