#!/bin/bash

cmd=$1
opts=$2

command_head="$cmd $opts -l -e '$3'"
shift 3

while (("$#")) && [ "$1" != -- ] ; do
  command_tail+="| xargs -r --null $cmd $opts -l -e '$1' "
  shift
done
shift

command_tail+="| xargs -r --null $cmd $opts -e '$1'"
shift

eval "$command_head $@ $command_tail"
