#!/bin/bash

opts=$1

command_head="rg $opts -l -e '$2'"
shift 2

while (("$#")) && [ "$1" != -- ] ; do
  command_tail+="| xargs -r --null rg $opts -l -e '$1' "
  shift
done
shift

command_tail+="| xargs -r --null rg $opts -e '$1'"
shift

eval "$command_head $@ $command_tail"
